[#2348] fix portable compilation issue
 allocation_state_unittest.cc:35:5:   required from here
 /usr/src/googletest/googletest/include/gtest/gtest.h:1392:11: error: no match for ‘operator==’ (operand types are ‘const boost::date_time::special_values’ and ‘const boost::posix_time::ptime’)
    if (lhs == rhs) {
        ~~~~^~~~~~