[stats_lettuce_fix] fix for the lettuce error: Not found statistics counter notifyoutv4
http://git.bind10.isc.org/~tester/builder//BIND10-lettuce/20120918121701-DebianLinux-x86_64-GCC/logs/lettuce.out
  AssertionError: Not found statistics counter notifyoutv4 for zone example.org.

Added waiting until the last requesting is finished instead of one-second
sleep. It should be done before checking the result of "Stats show" command via
bindctl.