[stats_lettuce_fix] fix for the lettuce error: Not found statistics counter notifyoutv4
http://git.bind10.isc.org/~tester/builder//BIND10-lettuce/20120918121701-DebianLinux-x86_64-GCC/logs/lettuce.out
  AssertionError: Not found statistics counter notifyoutv4 for zone example.org.

It has to wait at least for one second since the query to
b10-stats. b10-stats doesn't request to other module, e.g. b10-xfrout,
for less than one second, even if show command is invoked via
bindctl. This is for avoiding too frequent requests to b10-stats.