[#2727] introduce HAVE_MYSQL_GET_OPTION
Addresses error:
 mysql_connection_unittest.cc: In member function ‘virtual void {anonymous}::MySqlConnectionTest_connectionTimeout_Test::TestBody()’:
 mysql_connection_unittest.cc:633:77: error: ‘mysql_get_option’ was not declared in this scope
      EXPECT_EQ(0, mysql_get_option(mysql, MYSQL_OPT_CONNECT_TIMEOUT, &timeout));