Fix error: call of overloaded distance is ambiguous
The boost::iterators::distance function template is an adapted version
of std::distance for the Boost iterator traversal in 2.68 it has started
to fail with argument dependent lookup and compiler is erroring out

with

error: call of overloaded ‘distance'

boost implementation of distance is protected against being found by ADL

The way function is called in libdhcp means it will be found via ADL and
all namespaces will be considered which is providing problematic since
its getting it from both std:: and boost:: namespaces

so let it not rely on ADL by qualifying then calls with std:: namespace

Signed-off-by: Khem Raj <raj.khem@gmail.com>