[stats_lettuce_fix] fix for the lettuce error: AssertionError: Got 3, expected less than 3 as counter xfrrej
http://git.bind10.isc.org/~tester/builder/BIND10-lettuce/20120918210000-MacOS/logs/lettuce.out
  AssertionError: Got 3, expected less than 3 as counter xfrrej for zone _SERVER_

Removed the upper limits of the counter xfrrej. Because a xfer request might be
rejected greater than 3 times. This number of times might depend on something
like the environment or the platform or the rasing condition, where this
lettuce test is running.